[package]
name = "rusty"
version = "0.1.0"
authors = ["Jeremy Rubin <j@rubin.io>"]
edition = "2018"
build = "build.rs"

[dependencies]

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.19.0"
